/**
 * `.ryngo/annotations.md` — free-form notes attached to node ids.
 *
 * Append-only for the MVP. Each entry is a markdown section keyed by the
 * IR node id (`file:…`, `def:…`, `cell:…`, `pkg:…`). Multiple entries per
 * node are fine — they read like a comment thread.
 *
 *   ## node: def:src/auth/login.ts#authenticate
 *   > "this should accept a refresh token"
 *   > — alice, 2026-05-09
 *
 * Format chosen so an LLM that reads the raw file can obey it without any
 * parsing tooling.
 */
import { readMaybe, writeFile, todayISO } from "./storage.js";

const FILE = "annotations.md";

const HEADER =
  "# Ryngo annotations\n\n" +
  "Auto-generated by Ryngo. One entry per node, append-only. Edit by hand if you like.\n" +
  "Your AI tools (Cursor, Claude Code, etc.) read this file via the generated `.cursorrules` / `CLAUDE.md`.\n";

export async function read(repo) {
  return await readMaybe(repo, FILE);
}

/** `{ [nodeId]: count }` — how many annotation entries each node has. */
export async function countsByNode(repo) {
  const text = await readMaybe(repo, FILE);
  const out = {};
  const re = /^##\s+node:\s*(\S+)/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    out[m[1]] = (out[m[1]] || 0) + 1;
  }
  return out;
}

export async function append(repo, { nodeId, text, author }) {
  if (!nodeId || typeof nodeId !== "string") {
    throw new Error("append: `nodeId` is required");
  }
  if (!text || typeof text !== "string") {
    throw new Error("append: `text` is required");
  }
  const existing = (await readMaybe(repo, FILE)) || HEADER + "\n";
  const a = (author || "user").replace(/[\n\r]/g, " ").trim();
  const date = todayISO();
  // Quote each line of the note so it renders as a blockquote in the .md.
  const quoted = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => `> ${line}`)
    .join("\n");
  const entry = `\n## node: ${nodeId}\n${quoted}\n> — ${a}, ${date}\n`;
  const next = existing + entry;
  await writeFile(repo, FILE, next);
  return entry;
}
